# Be sure to restart your server when you modify this file.
#
# This file eases your Rails 7.0 framework defaults upgrade.
#
# Uncomment each configuration one by one to switch to the new default.
# Once your application is ready to run with all new defaults, you can remove
# this file and set the `config.load_defaults` to `7.0`.
#
# Read the Guide for Upgrading Ruby on Rails for more info on each option.
# https://guides.rubyonrails.org/upgrading_ruby_on_rails.html
#
# This is the stock template Rails ships via `rails app:update` for the 7.0
# hop (fetched verbatim from the `railties-7.0.10` gem installed for this hop
# via Gemfile.next, the same way Tasks 6/7 pulled the 6.0/6.1 templates).
# Per the roadmap's risk-tiered `load_defaults` ramp, this hop (Task 8) turns
# on `config.load_defaults 7.0` itself (guarded by `NextRails.next?` in
# config/application.rb) and leaves every individually-togglable behavior
# below commented out / pinned to its pre-7.0 default UNLESS noted otherwise
# — audit results below.

# `button_to` view helper will render `<button>` element, regardless of whether
# or not the content is passed as the first argument or as a block.
# Not flipped — this app's three `button_to` calls
# (devise/registrations/edit.html.erb, okrs/_okr.erb, okrs/_approval.erb) all
# pass a string label (not block content), so this toggle wouldn't change
# their behavior either way, but flipping the rendered element from
# `<input type="submit">` to `<button>` is still a markup change with no
# forcing function here; leaving it pinned avoids an unrelated CSS/JS risk
# (Foundation 5's button styling targets specific selectors).
# Rails.application.config.action_view.button_to_generates_button_tag = true

# `stylesheet_link_tag` view helper will not render the media attribute by default.
# Not flipped — no observed need; this app's `stylesheet_link_tag` calls
# don't pass an explicit `media:` option and no test asserts on the
# attribute, but there's no forcing function to change it this hop either.
# Rails.application.config.action_view.apply_stylesheet_media_default = false

# Change the digest class for the key generators to `OpenSSL::Digest::SHA256`.
# Changing this default means invalidate all encrypted messages generated by
# your application and, all the encrypted cookies. Only change this after you
# rotated all the messages using the key rotator.
# Not flipped — this app doesn't use Rails credentials/encrypted messages
# (config/app_config.yml is a plain YAML constant, not Rails credentials, per
# Task 6's audit); flipping this would only affect session/cookie signing,
# and there's no rotation plan in scope for this hop.
# Rails.application.config.active_support.key_generator_hash_digest_class = OpenSSL::Digest::SHA256

# Change the digest class for ActiveSupport::Digest.
# Not flipped — would invalidate ETags/cache keys app-wide; no forcing
# function, deferred like the key generator digest above.
# Rails.application.config.active_support.hash_digest_class = OpenSSL::Digest::SHA256

# Don't override ActiveSupport::TimeWithZone.name and use the default Ruby
# implementation.
# N/A — grepped app/ and lib/ for `TimeWithZone` usage relying on `#name`
# behavior; none found.
# Rails.application.config.active_support.remove_deprecated_time_with_zone_name = true

# Calls `Rails.application.executor.wrap` around test cases.
# Not flipped — changes test-environment query-cache/async-query behavior
# app-wide; auditing the full suite against this is a deliberate future
# follow-up, not bundled into this hop.
# Rails.application.config.active_support.executor_around_test_case = true

# Set both the `:open_timeout` and `:read_timeout` values for `:smtp` delivery method.
# N/A — no forcing function; mail delivery timeouts weren't an observed
# problem in this app's characterization tests.
# Rails.application.config.action_mailer.smtp_timeout = 5

# The ActiveStorage video previewer will now use scene change detection...
# N/A — this app doesn't use ActiveStorage (CarrierWave/MiniMagick handle
# uploads instead; see app/uploaders/, confirmed again this hop).
# Rails.application.config.active_storage.video_preview_arguments = ...

# Automatically infer `inverse_of` for associations with a scope.
# Not flipped — same reasoning as the 6.1 hop's `has_many_inversing`
# deferral: this app's scoped associations (e.g. `Task#users` through
# `key_results`) were never audited against automatic-inverse semantics.
# Rails.application.config.active_record.automatic_scope_inversing = true

# Raise when running tests if fixtures contained foreign key violations
# Not flipped — this app's fixtures were never audited for FK integrity
# (MySQL's InnoDB FK enforcement isn't even declared via `add_foreign_key`
# anywhere in db/schema.rb); turning this on could surface pre-existing
# fixture debt unrelated to this hop's Rails/Ruby bump.
# Rails.application.config.active_record.verify_foreign_keys_for_fixtures = true

# Disable partial inserts.
# Not flipped — would change every INSERT to reference all columns
# regardless of default; no forcing function, and this touches every model.
# Rails.application.config.active_record.partial_inserts = false

# Protect from open redirect attacks in `redirect_back_or_to` and `redirect_to`.
# FLIPPED ON this hop: audited every `redirect_to` call site in
# app/controllers/*.rb (roadmap Task 8's own instruction to check this
# specifically) — every one redirects to a named route/path helper or
# `root_url`/`root_path` (teams/comments/okrs/users/objectives/key_results/
# reports/oauth_applications/projects/work_logs controllers), never to a
# user-controlled or externally-sourced URL. No `redirect_to params[...]`
# or similar pattern found anywhere. Safe to enable as a security hardening
# with no behavior change for this app's actual redirects, confirmed by the
# full characterization suite staying green. Unconditional now that
# Gemfile.next has been promoted to become this Gemfile (both Gemfile and
# the new Gemfile.next run Rails 7.0+, which understands this config key).
Rails.application.config.action_controller.raise_on_open_redirects = true

# Change the variant processor for Active Storage.
# N/A — no ActiveStorage usage.
# Rails.application.config.active_storage.variant_processor = :vips

# Enable parameter wrapping for JSON.
# Not flipped — this app already has its own
# config/initializers/wrap_parameters.rb (`wrap_parameters format: [:json]`),
# which continues to apply regardless of this toggle; no need to duplicate
# or change it this hop.
# Rails.application.config.action_controller.wrap_parameters_by_default = true

# Specifies whether generated namespaced UUIDs follow the RFC 4122 standard...
# N/A — grepped for `Digest::UUID.uuid_v3`/`uuid_v5`; no callers found.
# Rails.application.config.active_support.use_rfc4122_namespaced_uuids = true

# Change the default headers to disable browsers' flawed legacy XSS protection.
# Not flipped — changes response headers app-wide (`X-XSS-Protection`,
# `X-Frame-Options`, etc.); no test asserts on these headers, but there's no
# forcing function to change them either, and security-header changes
# deserve their own deliberate review rather than a load_defaults side effect.
# Rails.application.config.action_dispatch.default_headers = { ... }

# ** Please read carefully, this must be configured in config/application.rb **
# Change the format of the cache entry.
# Not flipped — this app doesn't have a shared production cache store to
# worry about rolling back (default `:file_store`/`:memory_store` per
# environment, no Redis/Memcached deploy details in this repo), but changing
# cache-entry format mid-upgrade-ladder (more Rails hops still to come per
# roadmap Task 9) has no upside yet; deferred until the ladder is fully
# climbed. Would go in config/application.rb, NOT this file, if flipped.
# config.active_support.cache_format_version = 7.0

# Cookie serializer: 2 options
# Not flipped — this app never set `cookies_serializer` explicitly (grepped
# config/initializers and config/environments), so it's already on Rails'
# pre-7.0 default (`:marshal`). Migrating to `:json`/`:hybrid` is a
# deliberate follow-up (invalidates/needs-transition existing session
# cookies), not a side effect of this Ruby/Rails hop.
# Rails.application.config.action_dispatch.cookies_serializer = :json

# Change the return value of `ActionDispatch::Request#content_type` to the
# Content-Type header without modification.
# N/A this hop — Task 6's `new_framework_defaults_6_0.rb` audit already
# covered the sibling `ActionDispatch::Response#content_type` toggle (found
# N/A then, no code relies on the old parsed/stripped format); re-grepped
# app/ and lib/ for `request.content_type`/`response.content_type` again
# this hop, still no callers relying on the old behavior.
# Rails.application.config.action_dispatch.return_only_request_media_type_on_content_type = false

# Active Storage `has_many_attached` relationships will default to replacing...
# N/A — no ActiveStorage usage.
# Rails.application.config.active_storage.multiple_file_field_include_hidden = true

# ** Please read carefully, this must be configured in config/application.rb (NOT this file) **
# Disables the deprecated #to_s override in some Ruby core classes
# Not flipped — no forcing function; this app doesn't rely on the
# `Symbol#to_s`/`Module#to_s` frozen-string quirk this toggle addresses.
# config.active_support.disable_to_s_conversion = true
